set SERVEROUTPUT ON FORMAT WRAPPED
set APPINFO ON
SET VERIFY OFF

SET FEEDBACK OFF
SET TERMOUT OFF

column date_column new_value today_var
column scriptname new_value thescriptname;
column sessionname new_value sessionname;
column dbname new_value dbname;
select 
	SUBSTR(sys_context('USERENV', 'MODULE'), instr(sys_context('USERENV', 'MODULE'), ' ') +1) || '_' || to_char(sysdate, 'yyyymmdd') date_column,
  	sys_context('USERENV', 'MODULE') scriptname,
	sys_context('USERENV','SESSION_USER') sessionname,
	sys_context('USERENV','DB_NAME') dbname
from dual;
  
SPOOL &today_var..log

SET VERIFY ON
SET FEEDBACK ON
SET TERMOUT On
SET ECHO ON 

insert into appdba_util.scriptinventory (
SCRIPTNAME,
CREATEDATE,
SCHEMANAME,
DATABASE,
ROLLBACKIND,
FAILUREIND,
localGlobalInd)
values
('&thescriptname',
 sysdate,
 '&sessionname',
 '&dbname',
 'N',
 'N',
 'G');
commit;

REM INSERTING into SBMBUSINESSRULECONFIGURATION
SET DEFINE OFF;
Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R067','CA',systimestamp,'AYY',systimestamp,'AYY');

Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R068','CA',systimestamp,'AYY',systimestamp,'AYY');

Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R069','CA',systimestamp,'AYY',systimestamp,'AYY');


Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R067','CO',systimestamp,'AYY',systimestamp,'AYY');

Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R068','CO',systimestamp,'AYY',systimestamp,'AYY');

Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R069','CO',systimestamp,'AYY',systimestamp,'AYY');


Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R067','MD',systimestamp,'AYY',systimestamp,'AYY');

Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R068','MD',systimestamp,'AYY',systimestamp,'AYY');

Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R069','MD',systimestamp,'AYY',systimestamp,'AYY');


Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R067','NY',systimestamp,'AYY',systimestamp,'AYY');

Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R068','NY',systimestamp,'AYY',systimestamp,'AYY');

Insert into SBMBUSINESSRULECONFIGURATION (SBMBUSINESSRULETYPECD,STATECD,CREATEDATETIME,CREATEBY,LASTMODIFIEDDATETIME,LASTMODIFIEDBY) values ('R069','NY',systimestamp,'AYY',systimestamp,'AYY');


commit;

spool off
