set SERVEROUTPUT ON FORMAT WRAPPED
set APPINFO ON
SET VERIFY OFF

SET FEEDBACK OFF
SET TERMOUT OFF

column date_column new_value today_var
column scriptname new_value thescriptname;
column sessionname new_value sessionname;
column dbname new_value dbname;
select 
	SUBSTR(sys_context('USERENV', 'MODULE'), instr(sys_context('USERENV', 'MODULE'), ' ') +1) || '_' ||  sys_context('USERENV','SESSION_USER') || '_' ||sys_context('USERENV','DB_NAME')  || '_'|| to_char(sysdate, 'yyyymmdd') date_column,
  	sys_context('USERENV', 'MODULE') scriptname,
	sys_context('USERENV','SESSION_USER') sessionname,
	sys_context('USERENV','DB_NAME') dbname
from dual;

SPOOL &today_var..log

SET VERIFY ON
SET FEEDBACK ON
SET TERMOUT On
SET ECHO ON

INSERT into appdba_util.scriptinventory (
SCRIPTNAME,
CREATEDATE,
SCHEMANAME,
DATABASE,
ROLLBACKIND,
FAILUREIND,
localGlobalInd)
values
('&thescriptname',
 sysdate,
 '&sessionname',
 '&dbname',
 'N',
 'N',
 'G');
commit;

select count(*) from STATEPRORATIONCONFIGURATION;

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'AK' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('AK', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'AL' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('AL', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'AR' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('AR', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'AZ' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('AZ', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'DE' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('DE', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'FL' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('FL', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'GA' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('GA', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'HI' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('HI', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'IA' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('IA', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'IL' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('IL', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'IN' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('IN', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'KS' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('KS', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'LA' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('LA', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'ME' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('ME', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'MI' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('MI', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'MO' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('MO', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'MS' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('MS', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'MT' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('MT', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'NC' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('NC', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'ND' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('ND', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'NE' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('NE', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'NH' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('NH', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'NJ' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('NJ', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'NM' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('NM', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'NV' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('NV', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'OH' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('OH', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'OK' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('OK', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'OR' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('OR', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'PA' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('PA', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'SC' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('SC', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'SD' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('SD', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'TN' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('TN', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'TX' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('TX', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'UT' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('UT', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'VA' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('VA', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'WI' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('WI', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'WV' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('WV', '2017', '1');

MERGE INTO STATEPRORATIONCONFIGURATION USING DUAL ON ( STATECD = 'WY' and MARKETYEAR = '2017' ) WHEN MATCHED THEN UPDATE SET PRORATIONTYPECD = '1'  WHEN NOT MATCHED THEN INSERT(STATECD, MARKETYEAR, PRORATIONTYPECD) VALUES ('WY', '2017', '1');

select count(*) from STATEPRORATIONCONFIGURATION;

commit;

spool off