set SERVEROUTPUT ON FORMAT WRAPPED
set APPINFO ON
SET VERIFY OFF

SET FEEDBACK OFF
SET TERMOUT OFF

column date_column new_value today_var
column scriptname new_value thescriptname;
column sessionname new_value sessionname;
column dbname new_value dbname;
SELECT Substr(Sys_context('USERENV', 'MODULE'),
              Instr(Sys_context('USERENV', 'MODULE'), ' ')
                                                + 1)
       || '_'
       || To_char(SYSDATE, 'yyyymmdd')        date_column,
       Sys_context('USERENV', 'MODULE')       scriptname,
       Sys_context('USERENV', 'SESSION_USER') sessionname,
       Sys_context('USERENV', 'DB_NAME')      dbname
FROM   dual;

SPOOL &today_var..log

SET VERIFY ON
SET FEEDBACK ON
SET TERMOUT On

INSERT INTO appdba_util.scriptinventory
            (scriptname,
             createdate,
             schemaname,
             DATABASE,
             rollbackind,
             failureind,
             localglobalind)
VALUES      ('&thescriptname',
             SYSDATE,
             '&sessionname',
             '&dbname',
             'N',
             'N',
             'G');
commit;

set serveroutput on
set feedback on
set echo on


PROMPT Deleting data ...

TRUNCATE TABLE BATCHCYCLETOTAL REUSE STORAGE;
TRUNCATE TABLE BATCHERRORLOG REUSE STORAGE;
TRUNCATE TABLE BATCHPROCESSLOG REUSE STORAGE;
TRUNCATE TABLE DISPATCHEDPHYSICALDOCUMENT REUSE STORAGE;
TRUNCATE TABLE DISPATCHROUTINGMAP REUSE STORAGE;
TRUNCATE TABLE ERRORLEVELTYPE REUSE STORAGE;
TRUNCATE TABLE FEEDBACKLOG REUSE STORAGE;
TRUNCATE TABLE INSRNCMARKETCOVERAGETYPE REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANBNFTMETLTIERTYPE REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANEXCHGMARKETTYPE REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANRATEAREADFLTCHRG REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANRATEAREA REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANRATEAREAYBDF1747001 REUSE STORAGE;
TRUNCATE TABLE INSRNCPLAN REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANVARIANTCMPT REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANVARIANTCMPTTYPE REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANVARIANTCYBDF1747002 REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANYBDF1747000 REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANYEARMETALTRRATEAREA REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANYEARMETAYAL83253012 REUSE STORAGE;
TRUNCATE TABLE INSURANCEMARKETLEVEL REUSE STORAGE;
TRUNCATE TABLE INSURANCEMARKETLEVELTYPE REUSE STORAGE;
TRUNCATE TABLE INSURANCEMARKETLEVYBJL5305002 REUSE STORAGE;
TRUNCATE TABLE INSURANCEPLANDEFAULTCHARGE REUSE STORAGE;
TRUNCATE TABLE INSURANCEPLANMARKETLEVELSTATUS REUSE STORAGE;
TRUNCATE TABLE INSURANCEPLANMARKETLEVELTYPE REUSE STORAGE;
TRUNCATE TABLE INSURANCEPLANMARKEYBIC5817000 REUSE STORAGE;
TRUNCATE TABLE INSURANCEPLANMARKEYBJL5305003 REUSE STORAGE;
TRUNCATE TABLE INSURANCEPLANYEAR REUSE STORAGE;
TRUNCATE TABLE INVOICEPROGRAMTYPE REUSE STORAGE;
TRUNCATE TABLE INVOICETRANSACTION REUSE STORAGE;
TRUNCATE TABLE ISSUERLEVELTRANSACTION REUSE STORAGE;
TRUNCATE TABLE ISSUERRISKDEFAULTCHARGE REUSE STORAGE;
TRUNCATE TABLE ISSUERRISKREINSURANCEBATCH REUSE STORAGE;
TRUNCATE TABLE ISSUERRISKREINSURANCECYCLE REUSE STORAGE;
TRUNCATE TABLE ISSUERRISKREINSURANCE REUSE STORAGE;
TRUNCATE TABLE ISSUERUSERFEERATE REUSE STORAGE;
TRUNCATE TABLE MANUALADJUSTMENTDETAIL REUSE STORAGE;
TRUNCATE TABLE MANUALADJUSTMENTHEADER REUSE STORAGE;
TRUNCATE TABLE MANUALADJUSTMENTREASONTYPE REUSE STORAGE;
TRUNCATE TABLE METALTIERRISKADJUSTMENT REUSE STORAGE;
TRUNCATE TABLE PAYEELEVELTRANSACTION REUSE STORAGE;
TRUNCATE TABLE PAYMENTPROCERRORLEVEL REUSE STORAGE;
TRUNCATE TABLE PAYMENTPROCERRORLEVELTYPE REUSE STORAGE;
TRUNCATE TABLE PAYMENTPROCERRORTYPE REUSE STORAGE;
TRUNCATE TABLE PAYMENTPROCESSINGSTATUS REUSE STORAGE;
TRUNCATE TABLE PAYMENTPROCSTATUSTYPE REUSE STORAGE;
TRUNCATE TABLE PAYMENTTRANSSTATUSTYPE REUSE STORAGE;
TRUNCATE TABLE PHYSICALDOCUMENTDSPTCHDTYPE REUSE STORAGE;
TRUNCATE TABLE PHYSICALDOCUMENTFILETYPE REUSE STORAGE;
TRUNCATE TABLE PHYSICALDOCUMENT REUSE STORAGE;
TRUNCATE TABLE POLICYPAYMENTTRANS REUSE STORAGE;
TRUNCATE TABLE PREMIUMSTABILIZATIONBATCH REUSE STORAGE;
TRUNCATE TABLE PREMIUMSTABILIZATIONERRORLOG REUSE STORAGE;
TRUNCATE TABLE PREMIUMSTABILIZATIONREPORT REUSE STORAGE;
TRUNCATE TABLE PREMIUMSTBLZTNERRORWARNINGTYPE REUSE STORAGE;
TRUNCATE TABLE PREMIUMSTBLZTNTRANSACTION REUSE STORAGE;
TRUNCATE TABLE PREMIUMTRANSACTIONSTATUSTYPE REUSE STORAGE;
TRUNCATE TABLE REFERENCECODEMAPPING REUSE STORAGE;
TRUNCATE TABLE RISKREPORTTYPE REUSE STORAGE;
TRUNCATE TABLE SERVERENVIRONMENTTYPE REUSE STORAGE;
TRUNCATE TABLE STAGINGTRANSACTIONALDECISION REUSE STORAGE;
TRUNCATE TABLE STAGINGTRANSBATCHISSUER REUSE STORAGE;
TRUNCATE TABLE STATEMARKETLEVEL REUSE STORAGE;
TRUNCATE TABLE STATERISKPAYMENTBATCH REUSE STORAGE;
TRUNCATE TABLE STATERISKPAYMENTCYCLE REUSE STORAGE;
TRUNCATE TABLE STATERISKPAYMENT REUSE STORAGE;
TRUNCATE TABLE TARGETEFTAPPLICATIONTYPE REUSE STORAGE;
TRUNCATE TABLE TRANSACTIONLOGTYPE REUSE STORAGE;
TRUNCATE TABLE INSRNCPLANRATEAREADFLTCHRG REUSE STORAGE;
TRUNCATE TABLE DISPATCHROUTINGMA REUSE STORAGE;
TRUNCATE TABLE SERVERENVIRONMENTTYP REUSE STORAGE;
TRUNCATE TABLE PHYSICALDOCUMENTDSPTCHDTYPE REUSE STORAGE;
TRUNCATE TABLE PHYSICALDOCUMENTFILETYPE REUSE STORAGE;

Prompt Tables Truncated
SPOOL OFF
