
DELETE POLICYMEMBERADDRESS;
DELETE POLICYMEMBERDATE;
DELETE POLICYMEMBERLANGUAGEABILITY;
DELETE MEMBERPOLICYRACEETHNICITY;
DELETE POLICYSTATUS;
DELETE POLICYPREMIUM;
DELETE POLICYMEMBER;
DELETE POLICYPAYMENTTRANSSTATUS;
DELETE POLICYPAYMENTTRANS;
DELETE POLICYVERSION;
DELETE POLICYMEMBERVERSION;

DELETE STAGINGPOLICYMEMBERDATE;
DELETE STAGINGPOLICYSTATUS;
DELETE STAGINGPOLICYPREMIUM;
DELETE STAGINGPOLICYMEMBER;
DELETE STAGINGPOLICYVERSION;
DELETE STAGINGPOLICYMEMBERVERSION;

DELETE STAGING820PIPEBATCH;
DELETE ERRORWARNINGLOG;
DELETE BATCHRUNCONTROL;

DELETE SBMTRANSMSGADDITIONALERRORINFO;
DELETE SBMTRANSMSGVALIDATION;
DELETE SBMTRANSMSG;

DELETE SBMFILEARCHIVE;
DELETE STAGINGSBMFILE;
DELETE STAGINGSBMPOLICY;
DELETE SBMFILEERRORADDITIONALINFO;
DELETE SBMFILEERROR;
DELETE SBMFILEINFO;
DELETE STAGINGSBMGROUPLOCK;
DELETE SBMFILEPROCESSINGSUMMARY;

