DELETE POLICYMEMBERADDRESS            WHERE CREATEBY = ?;
DELETE POLICYMEMBERDATE               WHERE CREATEBY = ?;
DELETE POLICYSTATUS                   WHERE CREATEBY = ?;
DELETE POLICYPREMIUM                  WHERE CREATEBY = ?;
DELETE POLICYMEMBER                   WHERE CREATEBY = ?;
DELETE ERRORWARNINGLOG WHERE BATCHID = ?;
DELETE BATCHTRANSMSG                  WHERE CREATEBY = ?;  
DELETE TRANSMSGFILEINFO               WHERE CREATEBY = ?;
DELETE POLICYMEMBERVERSION            WHERE CREATEBY = ?;
DELETE POLICYVERSION                  WHERE CREATEBY = ?;
DELETE TRANSMSG                       WHERE PARENTTRANSMSGID IS NOT NULL AND CREATEBY = ?;
DELETE TRANSMSG                       WHERE CREATEBY = ?;
DELETE BATCHRUNCONTROL                WHERE JOB_INSTANCE_ID = ?;
DELETE STAGINGPLANLOCK				  WHERE BATCHID = ?;
DELETE BATCHRUNCONTROL